#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

// register the auto loader
require __DIR__."/bootstrap/autoload.php";

$app = require_once __DIR__."/bootstrap/app.php";

// run the Artisan application
$kernel = $app->make(Kernel::class);

$status = $kernel->handle($input = new ArgvInput, new ConsoleOutput);

// shutdown the application
$kernel->terminate($input, $status);

exit($status);
